CREATE TABLE Board (
    number INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(150) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    id VARCHAR(20) NOT NULL,
    attime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fixattime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file_name VARCHAR(100) DEFAULT NULL,
    file_path VARCHAR(100) DEFAULT NULL
);

CREATE TABLE users(
    name VARCHAR(20) NOT NULL,
    email VARCHAR(50) PRIMARY KEY NOT NULL,
    password VARCHAR(20) NOT NULL
);

CREATE TABLE comment(
    number INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    board_number INT UNSIGNED NOT NULL,
    id VARCHAR(20) NOT NULL,
    content VARCHAR(100) NOT NULL,
    attime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fixattime datetime DEFAULT NULL,
    FOREIGN KEY (board_number) REFERENCES Board(number) ON DELETE CASCADE
);

CREATE TABLE Notice (
    number INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(150) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    id VARCHAR(20) NOT NULL,
    attime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fixattime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file_name VARCHAR(100) DEFAULT NULL,
    file_path VARCHAR(100) DEFAULT NULL
);
