services:
    web:
        build: .
        volumes:
          - ./src:/var/www/html
        ports:
          - "9000:80"
    
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: user_info
            MYSQL_USER: manager
            MYSQL_PASSWORD: 1234
        
        ports:
          - "3306:3306"
